### ISSUE TITLE
Application startup failed

### ISSUE THREAD

**Issue by shrikant14** [jpsingarayar/SpellBlaze#2]
Hello,

I am not able to run the service.

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[2m2018-08-08 11:00:53.070[0;39m [31mERROR [spellcheck,,,][0;39m [35m35740[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at com.javaspell.spellcheck.main.ServiceApplication.main(ServiceApplication.java:16) [classes!/:1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [sc.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [sc.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [sc.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [sc.jar:1.0-SNAPSHOT]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:123) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:84) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:554) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:179) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        ... 16 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'proxyStreamServlet' defined in org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration: Bean instantiation via factory method failed; nested excep
tion is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'proxyStreamServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/http/Ht
tpMessage
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:234) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:215) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:91) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:79) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getServletContextInitializerBeans(EmbeddedWebApplicationContext.java:241) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:228) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_131]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'proxyStreamServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/http
/HttpMessage
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        ... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpMessage
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_131]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[sc.jar:1.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_131]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[sc.jar:1.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration.proxyStreamServlet(HystrixDashboardConfiguration.java:90) ~[spring-cloud-netflix-hystrix-dashboard-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$c7f03e41.CGLIB$proxyStreamServlet$0(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$c7f03e41$$FastClassBySpringCGLIB$$1cccee2a.invoke(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$c7f03e41.proxyStreamServlet(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpMessage
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[sc.jar:1.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
        ... 61 common frames omitted
Caused by: java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52) ~[sc.jar:1.0-SNAPSHOT]
        at sun.misc.Resource.getBytes(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_131]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_131]
        ... 68 common frames omitted

**Comment by jpsingarayar** [comment]
Im not able to replicate the above issue ... Build is passing each and every time... the project page has a Travis-CI notification too
